# netlify.toml - FIXED VERSION
[build]
  command = "CI= npm install && npm run build"
  publish = "dist"

# FIXED: Tell Netlify Dev to use the correct port for Vite
[dev]
  targetPort = 8888
  port = 3000
  autoLaunch = true

# Handle SPA routing - MUST be first and most specific
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Special handling for hash fragments in URLs containing access_token
# This is a critical fix for Supabase authentication redirects
[[redirects]]
  from = "/#access_token=*"
  to = "/auth/callback#access_token=:splat"
  status = 302
  force = true

# Special handling for URL-encoded hash fragments
[[redirects]]
  from = "/%23access_token=*"
  to = "/auth/callback#access_token=:splat"
  status = 302
  force = true

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Special redirect for hash fragments in auth callback
[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200
  force = true

# Ensure access tokens in URL fragments are preserved
[[redirects]]
  from = "/auth/callback#*"
  to = "/index.html"
  status = 200
  force = true

# Make environment variables available to Netlify Functions
[build.environment]
  # Override the NODE_ENV=production setting to ensure devDependencies are installed
  NPM_FLAGS = "--production=false"

# Configure Netlify Functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

# Configure function-specific environment variables
[functions.environment]
  # Allows VITE_ prefixed variables to be available in functions
  SUPABASE_URL = "${VITE_SUPABASE_URL}"
  SUPABASE_SERVICE_KEY = "${VITE_SUPABASE_SERVICE_KEY}"
  LOOPS_API_KEY = "${VITE_LOOPS_API_KEY}"
  APP_URL = "${VITE_APP_URL}"